### ISSUE TITLE
[Bug] Cannot scroll to the bottom of the emoji bar

### ISSUE THREAD

**Issue by ganruip** [TheWidlarzGroup/rn-emoji-keyboard#103]
### Describe of the bug:

When try to scroll to the bottom, it will rebound to the top automatically, it will prevent scrolling to the bottom. 
Encountered this issue on both static and modal mode.

**react native**: 0.70.3
**rn-emoji-keyboard**: 1.1.0
**device**: IOS 15.5

https://user-images.githubusercontent.com/15976895/203014010-0a32a4bb-b793-43e9-b6a2-0707a2708f30.mp4

**Comment by ganruip** [comment]
@jakex7 hey! can help take a look? thanks! 🙏

**Comment by shaheer2020** [comment]
I am still facing this issue in Android.
