### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by mominnawaf** [TheWidlarzGroup/rn-emoji-keyboard#110]
I want to change the bottom sheet colour to dark theme instead of just white.
It will be great if we have a prop such as mode light or dark
Reference image
![Screenshot_2022-12-28-22-28-54-77_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://user-images.githubusercontent.com/47545933/209846572-d6225d2a-15cd-4e7e-ae9c-ce6bc8bf29ee.jpg)

**Comment by mateki0** [comment]
Hey @mominnawaf actually you can do this with the prop "theme". We discovered yesterday that it's not well documented and we will update the docs. Here is the example of the darkMode picker

https://github.com/TheWidlarzGroup/rn-emoji-keyboard/blob/master/example/src/Dark/Dark.tsx

**Comment by mateki0** [comment]
I've also added theming section to the docs. You can check it out here:
https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/api/theme
https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/api/styles
