### ISSUE TITLE
Emoji disappears when moving between navigator screens

### ISSUE THREAD

**Issue by denissdubinin** [TheWidlarzGroup/rn-emoji-keyboard#113]
**Describe the bug**
Emoji disappears when moving between navigator screens by dragging from the left. It is happening only after the component is scrolled, even when you scroll bar to Y=0 position. It stays invisible unless you scroll again - touching is not working, only scrolling. The issue happens on both Xcode emulator and real device.

**To Reproduce**
1. Put emoji component into navigator screen
2. Navigate to your screen from other screen.
3. Scroll the emoji component
4. Try going to the previous screen by dragging it from the left

**Expected behavior**
Emoji component does not disappear and is rendered only when you stay on same screen and scroll it.

**Screenshots**
https://user-images.githubusercontent.com/15890438/210950353-7f938bfa-65b7-4afe-839b-5c8940661cfa.MP4

**Desktop (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.2

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.2

**Additional context**
```
"@react-navigation/bottom-tabs": "^6.5.0",
"@react-navigation/native": "^6.1.0",
"@react-navigation/native-stack": "^6.9.5",
"react": "18.1.0",
"react-native": "0.70.6",
"react-native-safe-area-context": "^4.4.1",
"react-native-screens": "^3.18.2",
"rn-emoji-keyboard": "^1.1.0",
"yarn": "^1.22.19"
```

**Comment by mateki0** [comment]
Hi, thanks for reporting this bug. I created a [PR](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/113) with fix. However I've discovered that it only appears on screen from @react-navigation/native-stack and the ones from @react-navigation/native works without any problem. The fix and new version should be deployed in this week but if you want instant fix and it's possible in your application you can consider changing the navigation library :)

**Comment by denissdubinin** [comment]
Thank you!!! I have tested and the screen is working properly now. Let me know if I can close the task or we wait for merge/release

**Comment by mateki0** [comment]
You're welcome, I'm happy that I could help you :) The issue will close automatically after merging PR
