### ISSUE TITLE
Request to publish a new release with latest

### ISSUE THREAD

**Issue by swaroopbutala** [TheWidlarzGroup/rn-emoji-keyboard#115]
Hello, 

Thanks for the component! It's well made and designed. 

Looks like there are a bunch of changes including persistence for reactions which are not on the latest release on npm. Can you please push the latest in a new release. 

Apologies, not sure if there is a way I could do myself.

Thanks!

**Comment by mateki0** [comment]
New release was published yesterday so I think that I can close this one. Thanks for using our library :)
