### ISSUE TITLE
Make the search smarter

### ISSUE THREAD

**Issue by oferRounds** [TheWidlarzGroup/rn-emoji-keyboard#116]
Would be good if we can make the search smarter. For example, using [this library](https://github.com/muan/emojilib), we can search for this 🙏 emoji, with other keywords beside its official name: 

 "wish",
 "namaste",
"highfive",
"pray",
"thanks"

This is a feature Slack and Apple also has – perhaps we can think of adding this? I may be able to do so if you point me to the right place

**Comment by oferRounds** [comment]
I see that [unicode-emoji-json](https://github.com/muan/unicode-emoji-json/tree/b274d24a2434eba0edc5fd7992583416561e3317) also mentions it

**Comment by crieggalder** [comment]
+1 - this would be a fantastic improvement!

**Comment by oferRounds** [comment]
@jakex7 can you point us please to what is needed and where in the library to add it?

**Comment by oferRounds** [comment]
@mateki0 what are your thoughts on this one?

**Comment by Okelm** [comment]
@oferRounds @crieggalder we working on this :)

**Comment by jakex7** [comment]
Hi @oferRounds @crieggalder
Thanks for suggesting this feature, it has been added in the latest [version 1.5.0](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/releases/tag/v1.5.0) 😃 I encourage you to update and test it yourself. If there is something that still needs improvement, or you have other ideas, let us know!
