### ISSUE TITLE
[Question] What is the reason the library allows only emojis of unicode < 12?

### ISSUE THREAD

**Issue by oferRounds** [TheWidlarzGroup/rn-emoji-keyboard#117]
I’m asking because due to this condition we don’t get latest emojis

**Comment by mateki0** [comment]
It's because if the problem reported few days ago in another issue - https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/122

It's safer to not allow the newest emojis as not all users will be able to use them. However as I said there I'm thinking of solution for it from native side.

**Comment by oferRounds** [comment]
cool, got you!

**Comment by oferRounds** [comment]
can we based create the emoji collection dynamically, based on the OS support of the current device? How does Slack, for example, handle this issue?

**Comment by mateki0** [comment]
Hi, sorry for late reply. I have no idea how other application handling that, but we will try to figure out our solution. We will soon post a roadmap with full list of improvements and approximate dates of releasing them.
