### ISSUE TITLE
Modal closed after select emoji

### ISSUE THREAD

**Issue by lamlengend98** [TheWidlarzGroup/rn-emoji-keyboard#124]
I want to select multi emoji in one time, but modal is closed after select an emoji
How can I select multiple without closing?

**Comment by lamlengend98** [comment]
@mateki0 can you take a look on this?

**Comment by mateki0** [comment]
Hi @lamlengend98 , there's separate props for this - https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/api/modal#allowmultipleselections
And here is the example in the code
https://github.com/TheWidlarzGroup/rn-emoji-keyboard/blob/master/example/src/SelectedEmojis/SelectedEmojis.tsx

**Comment by jakex7** [comment]
Exactly like @mateki0, `allowMultipleSelections` prop is what you're looking for. I'm closing this issue as it has been resolved, but feel free to reopen if you have any additional questions
