### ISSUE TITLE
Big emoji window is flicker before small window displayed

### ISSUE THREAD

**Issue by liellevibob** [TheWidlarzGroup/rn-emoji-keyboard#130]
**Describe the bug**
Big emoji window is flicker before small window displayed

**To Reproduce**
1. open any screen that can render keyboard and emoji picker
2. Open keyboard
3. Open emoji picker window

**Expected behavior**
The small emoji window should appear without the large window popping up before it

**Video attached**

https://user-images.githubusercontent.com/104358608/232470320-1faf8404-bf42-4398-a6d9-769f2961f327.MP4
 

 xcode simulator iOS 14 plus

**Smartphone **
 - Device:  iPhone6 Plus

**Comment by jakex7** [comment]
Hi, thanks for reporting this. I have created a PR #132 with the fix ⌨

**Comment by jakex7** [comment]
Hi @liellevibob, thanks for reporting this. I have created a PR #132 with the fix ⌨

**Comment by liellevibob** [comment]
@jakex7  Thank you very much!
