### ISSUE TITLE
Skin selector modal stays when you swipe to a different category

### ISSUE THREAD

**Issue by ManuViola77** [TheWidlarzGroup/rn-emoji-keyboard#135]
**Describe the bug**
If you have opened the skin selector modal and you swipe to another category, the skin selector modal doesn't close and it leaves inconsistent since is not above the correct emoji anymore.

**To Reproduce**
1. Open the EmojiPicker with params including enableSearchBar and categoryPosition="bottom"
2. Long tap to see the skin of one of the emojis
3. Swipe to the right to the next category
5. See that the skin selector modal still appears in the new category

**Expected behavior**
When I swipe to a different category the skin selector modal should hide since Im no longer seeing the emoji that is associated with it. 

**Screenshots**
![image](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/8755889/0e527e33-7a25-4871-8163-47045f465f0c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - It was reproducible in lots of devices both iOS and Android both simulator and real device.
 - "rn-emoji-keyboard": "^1.2.1" -> version we have for this library
 - "react-native": "0.71.4" -> react native version

**Additional context**
To fix this I added in the component `EmojiStaticKeyboard`, in the `handleScroll` function, I now call the `clearEmojiTonesData()` function to hide the skin tones modal.

**Comment by mateki0** [comment]
Hey, as for the other bug report we really appreciate your report. Maybe in the future you will open a PR with a fix? It's always nice to have a contribution to an OpenSource :)

**Comment by jakex7** [comment]
Hi @ManuViola77, thanks for reporting this issue.
@mateki0's fix has been merged and released in version 1.3.0. 

I'm closing this issue as solved, but If it's still valid, feel free to reopen 😃

**Comment by jakex7** [comment]
Hi @ManuViola77, thanks for reporting this issue.
@mateki0's fix has been merged and released in version 1.3.0. 

I'm closing this issue as solved, but If it's still valid, feel free to reopen 😃
