### ISSUE TITLE
Library looks very slow

### ISSUE THREAD

**Issue by DevDams** [TheWidlarzGroup/rn-emoji-keyboard#148]
**Describe the bug**
When I use the library in modal or static mode, my application runs very slowly only on the part of the app where i use the component to display or select an emoji.

**To Reproduce**
Here is the list of packages in my app
![Alt text](https://res.cloudinary.com/dams9ix/image/upload/v1690195422/Capture_d_%C3%A9cran_2023-07-24_104253_fep6ik.png)

**Expected behavior**
Everything should work normally without slowing down the application, and animations and emoji selection should take no time at all.

**Screenshots**
Here is a video showing how this runs in my app
[![](https://res.cloudinary.com/dams9ix/image/upload/v1690195310/Capture_d_%C3%A9cran_2023-07-24_104113_x3qbbt.png)](https://res.cloudinary.com/dams9ix/video/upload/v1690194891/petal_20230724_102702_agtjca.mp4)

**Smartphone:**
 - Device: Huawei Nova 3i
 - OS: Android 9
 - Browser: Expo Go

**Comment by Okelm** [comment]
Thanks for reporting @DevDams we'll look into this soon!

**Comment by samkit5495** [comment]
LOG  VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 3600, "dt": 1994, "prevDt": 767}

We also get this warning, is there any option to limit no of emojis we show ?

**Comment by KolissnikBogdan** [comment]
same, + 1
