### ISSUE TITLE
Cannot change the color of the searchBar text 

### ISSUE THREAD

**Issue by shanoysinc** [TheWidlarzGroup/rn-emoji-keyboard#154]
**Describe the bug**

`  styles={{
          searchBar: {
            // container: { backgroundColor: "red", color: "red" },
            text: {
              color: "white",
              backgroundColor: isDark ? colors.brand.black[700] : "red",
              borderRadius: 6,
            },
          },
          //   header: { backgroundColor: "red", color: "red", },
        }}`
**Screenshots**
![Simulator Screenshot - iPhone 14 - 2023-09-17 at 07 59 17](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/10425073/d2696c26-629c-4e3e-bd21-aff0594e4531)

**Smartphone (please complete the following information):**
 - Device: iphone 11 pro
 - OS: 16.4

**Comment by shanoysinc** [comment]
did a bit of digging in the code and you have to change it from the theme -> search ->placeholder
<img width="709" alt="Screenshot 2023-09-17 at 8 09 13 AM" src="https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/10425073/12ec6f62-57cc-4d1f-9942-b4cac7c318b4">

**Comment by jan-kozinski** [comment]
Hi, thanks for sharing your solution! Also please checkout our API reference docs, where all the customizable theme components are well described including their default colors https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/api/theme
