### ISSUE TITLE
[1.6.1] wrong scrollNav contentOffset on iPhone 15 Pro Max

### ISSUE THREAD

**Issue by efstathiosntonas** [TheWidlarzGroup/rn-emoji-keyboard#169]
**Describe the bug**
`scrollNav` offset is not calculated properly on iPhone 15 pro max, when changing categories the icons background is not centered.

**To Reproduce**
1. Run demo on iphone 13 and iphone 15 pro max emulators
2. while on iphone 13 the contentOffset is correct, on iPhone 15 pro max is not calculated properly

**Expected behavior**

**Screenshots**
left iPhone 13, right  iPhone 15 pro max

https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/717975/da870554-7e70-4948-b0ca-49450c8e9c2f

**Desktop (please complete the following information):**
 - OS:

**Smartphone (please complete the following information):**
 - Device: iPhone pro max emulator 
 - OS: 17.2

**Additional context**

**Comment by efstathiosntonas** [comment]
cc: @AnMiZa since you've opened a PR that "touches" the offesets, maybe you could take a look into it.

**Comment by efstathiosntonas** [comment]
nevermind, I was using react-native-size-matters in the `scrollNav` and this breaks the layout. After removing it everything went back to normal.

**Comment by AnMiZa** [comment]
@efstathiosntonas haha, that was quick 💨. I was just writing You a reply that I will take a look into it. Great that everything works fine. Have a great day 👋

**Comment by efstathiosntonas** [comment]
yeah, react-native-size-matters can be weird in large screens so that was my first goto to to check 😄
