### ISSUE TITLE
Ability to set emoji category sequence

### ISSUE THREAD

**Issue by rskim47** [TheWidlarzGroup/rn-emoji-keyboard#21]
**Is your feature request related to a problem? Please describe.**
I want to customize the sequence of the emoji categories 

**Describe the solution you'd like**
A emojiSequence prop ([emojiCateogry]) that can update the sequence of the emoji categories would allow us to customize the keyboard even further. 

Side note: thank you so much for such an amazing emoji keyboard library!

**Comment by jakex7** [comment]
Hello!
I'm sorry for the long waiting time, we had a lot of work to do.
That's a great idea, we're working on, and it will be able in next release! 🚀
