### ISSUE TITLE
When quickly changing the screen orientation it shows only a portion of the emojis

### ISSUE THREAD

**Issue by the-wrong-guy** [TheWidlarzGroup/rn-emoji-keyboard#34]
**Describe the bug**
When orientation the devices changes quickly it shows only a portion of the emojis

**To Reproduce**
1. Go to  https://snack.expo.dev/@chao-bhargab/vigorous-kiwi
2. Change the orientation of the device quickly as you can
3. See the error 

**Expected behavior**
The emoji should remain as it is

**Screenshots**
![Screenshot_2021-10-11-00-30-23-963_host exp exponent](https://user-images.githubusercontent.com/52911853/136710286-52ed3c80-3498-4a46-beb4-4cc4a70ea1e7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : 10 Home

**Smartphone (please complete the following information):**
 - Device: POCO X3
 - OS: Android 10

**Comment by phazei** [comment]
I also have also seen this issue on 1.7.0
