### ISSUE TITLE
Bringing up keyboard on iOS covers the emoji keyboard

### ISSUE THREAD

**Issue by pablaber** [TheWidlarzGroup/rn-emoji-keyboard#43]
**Describe the bug**
If you press the search bar on iOS and the keyboard comes up it covers the emoji keyboard. 

**To Reproduce**
1. Enable the search bar
2. Click on the search bar
3. When the keyboard comes up see that it covers everything. 

**Expected behavior**
Emoji keyboard avoids the iOS keyboard when it comes up. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12175437/139776432-b37ce644-3a9e-495b-97f6-48b556585819.jpeg)
![image](https://user-images.githubusercontent.com/12175437/139776446-171285fc-5eba-411a-9c56-78e4fada82a6.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.0.2

**Comment by arunim2405** [comment]
Slack solves this by expanding the selector so the search bar goes to the top, something similar can be implemented here as well

**Comment by arunim2405** [comment]
https://github.com/TheWidlarzGroup/rn-emoji-keyboard/pull/44
