### ISSUE TITLE
[Request]Horizontal scrolling with auto tab change just like iOS native emoji keyboard

### ISSUE THREAD

**Issue by umang-simform** [TheWidlarzGroup/rn-emoji-keyboard#48]
**Is your feature request related to a problem? Please describe.**
Currently, This package is really awesome but it only contains vertical scrolling, native iOS or slack emoji picker have horizontal scrolling that auto change the selected section

**Describe the solution you'd like**
It might require rework as current implementation is done with vertical scrolling in mind mainly.

**Describe alternatives you've considered**
NA

**Additional context**
Attached video of native emoji selector here:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61829970/150772037-12915a7c-6621-4dc3-b5c5-f0ef94d9e84b.gif)

**Comment by mateki0** [comment]
done in https://github.com/TheWidlarzGroup/rn-emoji-keyboard/pull/100 
It will be available in the next release
