### ISSUE TITLE
Emoji has transparency on Android

### ISSUE THREAD

**Issue by mgauthier** [TheWidlarzGroup/rn-emoji-keyboard#49]
A similar issue is here: https://github.com/EricPKerr/react-native-emoji/issues/32 and the solution appears to work. Can we add the default style prop here as well?

https://github.com/TheWidlarzGroup/rn-emoji-keyboard/blob/6735d6570624078381353f825697c7d834f4726f/src/components/SingleEmoji.tsx#L18

Proposed Change:
`<Text style={{ fontSize: emojiSize, color: '#000' }}>{item.emoji}</Text>`

**Comment by jakex7** [comment]
Hi @mgauthier,
Thank you for reporting this issue  🚀 
We've created new PR with that fix #50 and it will be merged and released soon 😄

**Comment by jakex7** [comment]
Hi @mgauthier 
I'm sorry that you had to wait so long. It should be fixed in v0.7.1 
Please let me know if that works for you 😄
