### ISSUE TITLE
Unable to select emoji while keyboard is open on Android

### ISSUE THREAD

**Issue by DavidBriglio** [TheWidlarzGroup/rn-emoji-keyboard#52]
**Describe the bug**
When the keyboard is showing (when searching), if the user taps an emoji (or anywhere on the screen), the emoji does not get selected and rather the keyboard just hides. It seems that the keyboard being open absorbs presses when the expected behaviour would be to allow clicking the content on the screen.

**To Reproduce**
1. Allow searching on component
2. Open the selector
3. Start searching (bringing up the keyboard)
4. Try and select an emoji while the keyboard is open
5. The keyboard will hide without selecting any emoji

**Expected behavior**
When the keyboard is open, the user should still be able to select an emoji.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 12

**Comment by jakex7** [comment]
Hi, @DavidBriglio 
Thank you for reporting this issue. It should be resolved is the nearest patch 🚀
Please let me know if that works for you 😄

**Comment by DavidBriglio** [comment]
Thank you for looking into this! Yes that works :smiley:
