### ISSUE TITLE
Feature request: Ability to move the category picker

### ISSUE THREAD

**Issue by wojtus7** [TheWidlarzGroup/rn-emoji-keyboard#6]
Ability to move the category picker so it can be embedded at the top of the modal.

![v-emoji-picker](https://user-images.githubusercontent.com/42337257/127010219-9de4c85b-7bee-4c9e-998b-a27402911c2d.jpg)

**Comment by jakex7** [comment]
@wojtus7 Feature added to [stable version in v0.3.0](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/releases/tag/v0.3.0).

**Comment by wojtus7** [comment]
Thanks ❤️
