### ISSUE TITLE
rn-emoji-keyboard not givning latest value of input after state change inside onEmojiSelected method

### ISSUE THREAD

**Issue by priyankagupta23pg** [TheWidlarzGroup/rn-emoji-keyboard#60]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jakex7** [comment]
Hi @priyankagupta23pg,
please follow the issue template and describe the problem in more detail. You can also include the code snippet that is causing problems in your app.
I'm waiting for reply with more informations 😃

**Comment by jakex7** [comment]
Hi @priyankagupta23pg, 
I'm closing this issue because you didn't provide to us any required details. It looks like a problem with your implementation so I encourage you to read our documentation
https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/documentation/start
