### ISSUE TITLE
Upgrade emoji version (iOS)

### ISSUE THREAD

**Issue by BenCoDev** [TheWidlarzGroup/rn-emoji-keyboard#61]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I can't select the latest emoji released like 🦦 in my App (surfing app).

**Describe the solution you'd like**
I would like to display all emojis including the latest emojis 

**Describe alternatives you've considered**
I was looking at a way to extend/patch the emojis catalog

**Additional context**
N/A

**Comment by mateki0** [comment]
Hey @BenCoDev, unfortunatelly even the newest version of the library which we are using for generating emojis list doesn't have this particular emoji. But using patch-package you can add your own emojis here is the instruction:
1. Go to node_modules/rn-emoji-keyboard/src/assets/emojis.json
2. Find appropriate category, which are sorted with 'title' property.
3. Add your icon:
`
{
    "title": "animals_nature",
    "data": [
      { "emoji": "🦦", "name": "ottel", "v": "12.0", "toneEnabled": false },
      ...
`

**Comment by mateki0** [comment]
Unicode package is bumped to the newest version and here is the instruction how to add own emoji so I will close this issue for now. Please reopen if needed :)

**Comment by BenCoDev** [comment]
Thanks a lot for the follow up 🦫
