### ISSUE TITLE
App crashed on production, error provided.

### ISSUE THREAD

**Issue by abdullahIsa** [TheWidlarzGroup/rn-emoji-keyboard#82]
Hello, while trying to open emoji-keyboard in production mode, i get this error below and it's a very long error, I don't know what could be the cause, thanks.

![Screenshot_2022-09-03-15-18-37-48_63bab2abbbd3d656a9c3a703ebaa25b9](https://user-images.githubusercontent.com/49385380/188260744-30b635db-d236-4ba8-9bdb-d940f0beb063.jpg)

**Comment by abdullahIsa** [comment]
Issue fixed, error was due to react-native-skia

Solution:
added this in proguard-rules.pro due to crash error https://github.com/Shopify/react-native-skia/issues/357#issuecomment-1092118277
-keep public class com.shopify.reactnative.skia.* {*;}

**Comment by ddikodroid** [comment]
> Hello, while trying to open emoji-keyboard in production mode, i get this error below and it's a very long error, I don't know what could be the cause, thanks.
> 
> ![Screenshot_2022-09-03-15-18-37-48_63bab2abbbd3d656a9c3a703ebaa25b9](https://user-images.githubusercontent.com/49385380/188260744-30b635db-d236-4ba8-9bdb-d940f0beb063.jpg)

hi, saw your issue. could you tell me how to show the error log like that on production? thanks in advance

**Comment by abdullahIsa** [comment]
> > Hello, while trying to open emoji-keyboard in production mode, i get this error below and it's a very long error, I don't know what could be the cause, thanks.
> > ![Screenshot_2022-09-03-15-18-37-48_63bab2abbbd3d656a9c3a703ebaa25b9](https://user-images.githubusercontent.com/49385380/188260744-30b635db-d236-4ba8-9bdb-d940f0beb063.jpg)
> 
> hi, saw your issue. could you tell me how to show the error log like that on production? thanks in advance

Hello i am using **react-native-exception-handler**  [`https://github.com/a7ul/react-native-exception-handler`](https://github.com/a7ul/react-native-exception-handler) works well for me, all the best.
