### ISSUE TITLE
Question: option to disable search scroll animation

### ISSUE THREAD

**Issue by oferRounds** [TheWidlarzGroup/rn-emoji-keyboard#91]
When search results gets updated, it does so with an animation
I’d like to remove the animation (not needed in my opinion), happy to do a pr – would you be able to direct to the relevant place in code?

Thank you for this library!

**Comment by oferRounds** [comment]
I now see in the decimation that it seems that originally it was with no animation
https://thewidlarzgroup.github.io/rn-emoji-keyboard/docs/documentation/Examples/search

This is what I’m looking for :)

**Comment by mateki0** [comment]
Hey @oferRounds I've created a [PR](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/pull/93) with the functionality that you've requested. It will allow you to turn off the animation by setting new `enableSearchAnimation` props to false. Till we merge and release new version. You can use patch-package to disable it in your project basing on mine changes.

**Comment by oferRounds** [comment]
yayyyyyyyyyyy
Thank you!!!! Looks great!
