### ISSUE TITLE
Package Import causes compiler error `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by jakecronin** [TheWidlarzGroup/rn-emoji-keyboard#97]
This looks like an awesome package, but I am struggling to get it to work.

**Describe the bug**
Adding `import EmojiPicker from 'rn-emoji-keyboard';` in code metro error: 

```
Error: ENOENT: no such file or directory
```

**To Reproduce**
1. `npm i rn-emoji-keyboard`
2. add `import EmojiPicker from 'rn-emoji-keyboard` to a component
3. Refresh metro and notice error.

**About**
 - OS: Mac OS 12.6, M1 Pro
 - iPhone physical device, iOS 17
 - "react-native": "0.67.4",
-  "rn-emoji-keyboard": "^1.0.0",
- Hermes enabled/disabled doesn't matter. Both cause issue.

**Comment by mateki0** [comment]
Hey @jakecronin. Can you show me all of your installed packages? Did you try to clear pods and install them again?

**Comment by jakex7** [comment]
I'm closing this issue due to the author's inactivity. If the problem is still valid, feel free to reopen this issue
